fix

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -120,23 +120,6 @@ else
 fi
 
 
-if [[ ${AUTO_MODE} == 1 ]]; then
-    _base=$(get 0)
-    COLOR[background]="${_base}"
-    COLOR[0]=$(rgb_value "${_base}" "+10%")
-    COLOR[8]=$(rgb_value "${_base}" "+25%")
-
-elif [[ ${AUTO_MODE} == 2 ]]; then
-    _base=$(get 0)
-    COLOR[background]=$(rgb_value "${_base}" "-10%")
-    COLOR[8]=$(rgb_value "${_base}" "+15%")
-
-elif [[ ${AUTO_MODE} ]]; then
-    fatal "Invalid mode '${AUTO_MODE}' from auto resolve colors"
-    exit 1
-fi
-
-
 # Replace defined colors
 for i in ${!_commands[@]}; do
     MOD=( ${_commands[$i]} )
@@ -173,6 +156,36 @@ for i in ${!_commands[@]}; do
             [[ $(get $i) == $(get $j) || ${_mod} ]] && \
                 COLOR[$j]=$(rgb_value "$(get $i)" "$_val")
         done
+        ;;
+
+    --mode)
+        if [[ ${_val} == 1 ]]; then
+            _base=$(get 0)
+            COLOR[background]="${_base}"
+
+            if [[ ${GTK_APPLICATION_PREFER_DARK_THEME:-1} == 1 ]]; then
+                COLOR[0]=$(rgb_value "${_base}" "+10%")
+                COLOR[8]=$(rgb_value "${_base}" "+25%")
+            else
+                COLOR[0]=$(rgb_value "${_base}" "-10%")
+                COLOR[8]=$(rgb_value "${_base}" "-25%")
+            fi
+
+        elif [[ ${_val} == 2 ]]; then
+            _base=$(get 0)
+
+            if [[ ${GTK_APPLICATION_PREFER_DARK_THEME:-1} == 1 ]]; then
+                COLOR[background]=$(rgb_value "${_base}" "-10%")
+                COLOR[8]=$(rgb_value "${_base}" "+15%")
+            else
+                COLOR[background]=$(rgb_value "${_base}" "+10%")
+                COLOR[8]=$(rgb_value "${_base}" "-15%")
+            fi
+
+        elif [[ ${_val} ]]; then
+            fatal "Invalid mode '${_val}' from auto resolve colors"
+            exit 1
+        fi
         ;;
 
     --fill)
